### ISSUE TITLE
PR to pandas

### ISSUE THREAD

**Issue by twiecki** [femtotrader/pandas_datareaders#3]
What are you thoughts on contributing this to Pandas? I'm sure they'd be appreciative.

**Comment by femtotrader** [comment]
They can take the code if they want. You can also fork and send a PR if you want.

but see this before https://github.com/pydata/pandas/issues/8713 and
https://github.com/pydata/pandas/issues/8961
see also https://github.com/pydata/pandas/issues/6456

syntax is slightly different between this version of "DataReader" (which is an object) and Pandas one (which is a function)

see for example test:

https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_google_finance_daily.py

New version:

    df= DataReader("GoogleFinanceDaily", expire_after=expire_after).get(symbol, start, end)


instead of

    df = web.DataReader(symbol, 'google', start, end)

so Pandas doc needs to be modified accordingly

Moreover I wonder if such a PR was accepted if we need to also keep previous syntax and warm users that this syntax is deprecated

I've done one file per DataReader and one file per DataReader test.
I think it's cleaner.

Such a PR will add `requests` as a requirement for Pandas (see @TomAugspurger @jreback )

**Comment by twiecki** [comment]
Thanks @femtotrader. Seems like they have pretty good arguments for keeping this separate which is fine. This could easily be an optional dependency for `zipline`.

**Comment by femtotrader** [comment]
I also see "requests_cache is relatively transparent, but I am not sure on how unreasonable it is.

If I have a function that gets historical data from yahoo, I feel like the caching should be done by choice by the user."

I don't see any "good arguments" in fact but that's probably a misunderstanding of english from my side.

In fact the "problem" of DataReaders is not clear see https://github.com/pydata/pandas/pull/9195

I really think that we should DISCUSS about it here: https://github.com/pydata/pandas/issues/8961

Thanks for closing this issue ;-)

**Comment by twiecki** [comment]
Well, seems like they say it's out of scope. But I agree that it should either be completely excluded or extended then.
